// Site-wide settings. Change SITE_URL when the site moves to a custom domain, then rebuild:
// canonical links, Open Graph URLs, robots.txt and sitemap.xml all come from it.

export const SITE = {
  url: 'https://how-much-do-i-need.freewebtoolss.workers.dev',
  name: 'How Much Do I Need?',
  tagline: 'Simple calculators for figuring out how much material, space, or quantity you need.',
  repo: 'https://github.com/recentart/how-much-do-i-need',
  themeColor: '#1d4ed8',
};

// Advertising (Adsterra banners). Nothing ad-related is rendered until at least one unit below
// has both a key and a script URL. To fill a unit: in Adsterra, Websites -> Get code for a banner
// of that size, then copy the key (from atOptions) and the script URL here.
//
// Each ad runs inside its own sandboxed frame page (/ads/<unit>.html, generated by the build), so
// ad code can't read the calculator or redirect the page. Visitors whose time zone is in the EU,
// EEA, UK or Switzerland see a consent bar first; everyone can change their choice with
// "Ad choices" in the footer.
export const ADS = {
  network: 'Adsterra',
  privacyUrl: 'https://adsterra.com/privacy-policy/',
  // Shown on the privacy page while ads are on. Update it when ads are switched on or changed.
  privacyUpdated: '3 October 2026',
  units: {
    'banner-320x50': { width: 320, height: 50, key: '', src: '' },
    'banner-468x60': { width: 468, height: 60, key: '4ba2ba2a67ab949bb2fda8883d5972e1', src: 'https://bauval.org/22/4ba2ba2a67ab949bb2fda8883d5972e1' },
    'box-300x250': { width: 300, height: 250, key: '', src: '' },
  },
  // Where ads go. Each slot shows the widest of its units that fits the space, and only loads when
  // it scrolls near the screen. minViewport keeps the sidebar ad to wide screens.
  slots: {
    'below-result': { units: ['banner-468x60', 'banner-320x50'] },
    sidebar: { units: ['box-300x250'], minViewport: 1100 },
  },
};

export const adUnitReady = (u) => Boolean(u && u.key && /^https:\/\//.test(u.src));
export const adsEnabled = (ads = ADS) => Object.values(ads.units).some(adUnitReady);
